#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  設定関連タスク
#
---

# Ubuntu用の追加ルート設定
- name: Configure additional routes (Ubuntu)
  include_tasks: config-ubuntu-add-routes.yml
  when:
    - ansible_facts.os_family == "Ubuntu"
    - additional_network_routes is defined
    - additional_network_routes | default([]) | length > 0

# RHEL用の追加ルート設定
- name: Configure additional routes (RHEL)
  include_tasks: config-rhel-add-routes.yml
  when:
    - ansible_facts.os_family == "RedHat"
    - additional_network_routes is defined
    - additional_network_routes | default([]) | length > 0
