#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  GRUB設定関連タスク Debian系


# update Grub
- name: Update grub
  ansible.builtin.shell: |
    update-grub
  when:
    - ansible_facts.os_family == 'Debian'
  become: true
  register: _result
  changed_when: _result.rc == 0
