#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  タスクメイン部
#
#  include_tasksで他のタスクを読み込む
#

# 最初に変数設定を読み直す ( role単独で実行可能とするため )
- name: "Load Params"
  ansible.builtin.include_tasks: load-params.yml
- name: "Package"
  ansible.builtin.include_tasks: package.yml
- name: "Directory"
  ansible.builtin.include_tasks: directory.yml
- name: "User Group"
  ansible.builtin.include_tasks: user_group.yml
- name: "Service"
  ansible.builtin.include_tasks: service.yml
- name: "Config K8Sworker Firewall"
  ansible.builtin.include_tasks: config-k8sworker-firewall.yml
  when: enable_firewall | default(false)
- name: "Config Irq Balance"
  ansible.builtin.include_tasks: config-irq-balance.yml
  when:
    - (k8s_reserved_system_cpus_default | default('',true)) | length > 0
- name: "Config Shielding"
  ansible.builtin.include_tasks: config-shielding.yml
  when:
    - (k8s_reserved_system_cpus_default | default('',true)) | length > 0
- name: "Config Worker Node"
  ansible.builtin.include_tasks: config-worker-node.yml
  when:
    - (k8s_reserved_system_cpus_default | default('',true)) | length > 0
- name: "Config"
  ansible.builtin.include_tasks: config.yml
- name: "Config Cilium Bgp Cplane"
  ansible.builtin.include_tasks: config-cilium-bgp-cplane.yml
  when:
    - k8s_bgp is defined
    - k8s_bgp.enabled | default(false)
