#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  kubelet サービス起動処理実体
#
# notify の kubelet_restarted_and_enabled に対応
- name: "Kubelet_restarted_and_enabled"
  listen: "kubelet_restarted_and_enabled"
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true
    enabled: true
  become: true
