#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
- ansible.builtin.import_tasks: kubelet.yml
- ansible.builtin.import_tasks: reboot-node.yml
- ansible.builtin.import_tasks: reload-firewall.yml
