#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  サービス起動ハンドラ
- name: "Reload Sysctl"
  ansible.builtin.import_tasks: reload-sysctl.yml
- name: "Restart Frr"
  ansible.builtin.import_tasks: restart-frr.yml
