#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  サービス起動ハンドラ
- ansible.builtin.import_tasks: reload-sysctl.yml
- ansible.builtin.import_tasks: restart-frr.yml