kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "multus-cni.serviceAccountName" . }}
  labels:
    {{- include "multus-cni.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "multus-cni.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "multus-cni.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
