#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  サービス起動ハンドラ
#
- name: "Restart Timesyncd"
  ansible.builtin.import_tasks: restart-timesyncd.yml
- name: "Restart Chrony"
  ansible.builtin.import_tasks: restart-chrony.yml
