#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.

# systemd-timesyncdを再起動する
- name: Restart_timesyncd
  listen: "restart_timesyncd"
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: true
  become: true
  when: ntp_client_is_systemd_timesyncd
