#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  multusテスト用podファイル作成タスク
#

# テスト用Podのマニュフェスト生成
- name: Setup a test pod manifest for Multus
  ansible.builtin.template:
    src: app-pod.yml.j2
    dest: "{{ k8s_multus_config_dir }}/app-pod.yml"
    owner: root
    group: root
    mode: 0644
    backup: no
