#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  タスクメイン部
#
#  include_tasksで他のタスクを読み込む
#

# 最初に変数設定を読み直す ( role単独で実行可能とするため )
- name: "Load Params"
  ansible.builtin.include_tasks: load-params.yml
- name: "Package"
  ansible.builtin.include_tasks: package.yml
- name: "Directory"
  ansible.builtin.include_tasks: directory.yml
- name: "User Group"
  ansible.builtin.include_tasks: user_group.yml
- name: "Service"
  ansible.builtin.include_tasks: service.yml
- name: "Config Cleanup Multus"
  ansible.builtin.include_tasks: config-cleanup-multus.yml
  when:
    - k8s_multus_enabled | default(false)
- name: "Config Multus"
  ansible.builtin.include_tasks: config-multus.yml
  when:
    - k8s_multus_enabled | default(false)
    - not (k8s_multus_kubectl_apply_enabled | default(false))
- name: "Config Kubectl Applied Multus"
  ansible.builtin.include_tasks: config-kubectl-applied-multus.yml
  when:
    - k8s_multus_enabled | default(false)
    - k8s_multus_kubectl_apply_enabled | default(false)
- name: "Directory Multus Test Pod"
  ansible.builtin.include_tasks: directory-multus-test-pod.yml
  when: k8s_multus_enabled | default(false)
