#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  タスクメイン部
#
#  include_tasksで他のタスクを読み込む
#

# 最初に変数設定を読み直す ( role単独で実行可能とするため )
- include_tasks: load-params.yml
- include_tasks: package.yml
- include_tasks: directory.yml
- include_tasks: user_group.yml
- include_tasks: service.yml
- include_tasks: config-cleanup-multus.yml
  when:
    - k8s_multus_enabled | default(false)
- include_tasks: config-multus.yml
  when:
    - k8s_multus_enabled | default(false)
    - not (k8s_multus_kubectl_apply_enabled | default(false))
- include_tasks: config-kubectl-applied-multus.yml
  when:
    - k8s_multus_enabled | default(false)
    - k8s_multus_kubectl_apply_enabled | default(false)
- include_tasks: directory-multus-test-pod.yml
  when: k8s_multus_enabled | default(false)
