#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  パッケージ関連処理
---

# kea-dhcpサーバーパッケージのインストール
- name: install kea-dhcp server packages
  package:
    name: "{{ kea_dhcp4_server_packages }}"
    state: present
  become: true
