#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  dhcp4 server サービス起動ハンドラ
#
---
# kea-dhcp4サーバーの再起動
- name: restart_kea_dhcp4_server
  listen: "restart_kea_dhcp4_server"
  service:
    name: "{{ kea_dhcp4_server_service }}"
    state: restarted
  become: true