#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#  ロール固有変数のデフォルト値
#  group_vars/all/all.yml やhost_varsで上書き可能とするため,
#  ロール名/defaults/main.yml に定義している
---

# openldap ユーザ名
# osixia/openldapのopenldapユーザID, グループIDは911
openldap_server_user: 911
openldap_server_grp: 911
openldap_docker_dir: "/data/openldap/docker"
openldap_scripts_dir: "/data/openldap/scripts"
openldap_database_dir: "/data/openldap/slapd/database"
openldap_config_dir: "/data/openldap/slapd/config"
openldap_service_port: 389
openldap_wait_host_stopped: "127.0.0.1"
openldap_wait_host_started: "{{ inventory_hostname }}"
openldap_wait_timeout: 600
openldap_wait_delay: 5
openldap_wait_sleep: 2
openldap_enable_ipv6: true
