#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  サービス起動ハンドラ
#
# 処理を直接書かずにincludeすること
# 例:
# - import_tasks: docker.yml

- name: "Reload Sysctl"
  ansible.builtin.import_tasks: reload-sysctl.yml
