#  -*- mode: yaml; coding: utf-8; line-endings: unix -*-
#  SPDX-License-Identifier: BSD-2-Clause
#
#  Copyright (c) 2025 TAKEHARU KATO
#  This file is distributed under the two-clause BSD license.
#  For the full text of the license, see the LICENSE file in the project root directory.
#  このファイルは2条項BSDライセンスの下で配布されています。
#  ライセンス全文はプロジェクト直下の LICENSE を参照してください。

#
#  ロール固有変数 ( 高優先度 )
#  defaults/main.yml よりも高い優先度を持つ変数をここで定義
#
---

# CRD API バージョン ( K8s v1.31 互換 )
virtualcluster_crd_apiversion: "apiextensions.k8s.io/v1"

# Virtual Cluster CRD API グループバージョン
virtualcluster_api_group: "tenancy.x-k8s.io"
virtualcluster_api_version: "v1alpha1"
