#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#

# 最初に変数設定を読み直す ( role単独で実行可能とするため )
- ansible.builtin.include_tasks: load-params.yml
- ansible.builtin.include_tasks: package.yml
# Dockerfileからコンテナを作成するために
# Dockerを起動する処理をdirectory.ymlの前に実行
- ansible.builtin.include_tasks: service.yml
- ansible.builtin.include_tasks: directory.yml
- ansible.builtin.include_tasks: docker-backup-image.yml
  when:
    - build_docker_ce_backup_container_image|default(false)|bool
- ansible.builtin.include_tasks: user_group.yml
- ansible.builtin.include_tasks: config.yml
