#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright (c) 2025 Takeharu KATO
#
#  ファイル・ディレクトリ作成関連タスク
#
---

# Virtual Clusterインスタンスの設定ファイル格納ディレクトリを作成
- name: "Create Virtual Cluster instances configuration directory"
  ansible.builtin.file:
    path: "{{ vcinstances_config_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true
