#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ロール固有変数のデフォルト値
#  group_vars/all/all.yml やhost_varsで上書き可能とするため,
#  ロール名/defaults/main.yml に定義している

# radvdがバインドするインターフェース
radvd_nic: "{{ gpm_mgmt_nic | default(mgmt_nic, true) }}"
# ルーター広告の最小送信間隔 (秒)
radvd_router_advertisement_min_interval: 30
# ルーター広告の最大待機間隔(広告周期) (秒)
radvd_router_advertisement_max_interval: 100
# radvdのルーター広告設定プレフィックス
radvd_router_advertisement_prefix: "{{ gpm_mgmt_ipv6_prefix }}/{{ gpm_mgmt_ipv6_addr_prefix_len }}"
# ルーター広告の可到達時間 (ミリ秒)
radvd_router_advertisement_reachable_time: 3000
# ルーター広告の再送時間 (ミリ秒)
radvd_router_advertisement_retrans_timer: 1000
# ルーター広告の有効期限 (秒)
# デフォルトルートを配布する場合は, 0より大きい値を設定すること
# AdvRtrAdvInterval (radvd_router_advertisement_max_interval) の3倍が推奨値
radvd_router_advertisement_default_lifetime: 300
# radvdのルーター広告設定プレフィックスの有効期限 (秒), 'infinity'を設定すると無期限
radvd_router_advertisement_prefix_valid_lifetime: 'infinity'
# radvdのルーター広告設定プレフィックスの優先期限 (秒), 'infinity'を設定すると無期限
radvd_router_advertisement_prefix_preferred_lifetime: 'infinity'


# radvdのRDNSSサーバーのリスト
radvd_dns_servers:
  - "{{ ipv6_name_server1 }}"
  - "{{ ipv6_name_server2 }}"
radvd_search_domains:
  - "{{ dns_domain }}"