#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ロール固有変数のデフォルト値
#  group_vars/all/all.yml やhost_varsで上書き可能とするため,
#  ロール名/defaults/main.yml に定義している
---

# Rancherオペレータユーザ設定
rancher_user: "rancher"

#  Rancher起動待ちタイムアウト(単位:秒)
rancher_start_timeout: 300

# Rancherサービスポート
rancher_service_port: 443

# Rancherサービス待機設定
# Rancherサービス停止を待ち合わせる(接続先)ホスト名/IPアドレス
rancher_wait_host_stopped: "127.0.0.1"
# Rancherサービス開始を待ち合わせる(接続先)ホスト名/IPアドレス
rancher_wait_host_started: "{{ inventory_hostname }}"
# Rancherサービス待ち合わせ時間(単位: 秒)
rancher_wait_timeout: "{{ rancher_start_timeout }}"
# Rancherサービス待ち合わせる際の開始遅延時間(単位: 秒)
rancher_wait_delay: 5
# Rancherサービス待ち合わせる際の待機間隔(単位: 秒)
rancher_wait_sleep: 2
# Rancherサービス待ち合わせる際の接続元ホスト名/IPアドレス
rancher_wait_delegate_to: "localhost"

# 証明書格納先ディレクトリ
rancher_cert_dir: "/etc/rancher/ssl"

# 永続化データ格納先ディレクトリ
rancher_data_dir: "/var/lib/rancher"

# Rancherイメージ
rancher_image: "rancher/rancher:latest"
