#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
# sysctlのリロードハンドラ
- name: "Reload sysctl settings from bastion_config role"
  listen: "bastion_config_reload_sysctl"
  ansible.builtin.command: sysctl --system
  changed_when: false
  become: true
