#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  frrパッケージ関連処理
---


- name: Install FRR (Debian family)
  ansible.builtin.package:
    name: "{{ frr_packages }}"
    state: present

- name: Enable and start FRR service
  ansible.builtin.service:
    name: "{{ frr_svc_name }}"
    enabled: true
    state: started

- name: Deploy IPv4/IPv6 forwarding sysctl drop-in
  ansible.builtin.template:
    src: "90-frr-forwarding.conf.j2"
    dest: "/etc/sysctl.d/90-frr-forwarding.conf"
    owner: root
    group: root
    mode: "0644"
  notify: "reload_sysctl"

- name: Deploy FRR configuration
  ansible.builtin.template:
    src: "frr.conf.j2"
    dest: "/etc/frr/frr.conf"
    owner: frr
    group: frr
    mode: "0640"
  notify: "restart_frr"
