#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ハンドラ定義
#
- ansible.builtin.import_tasks: disable-gui.yml
- ansible.builtin.import_tasks: sysctl.yml
- ansible.builtin.import_tasks: reboot-node.yml
