#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ハンドラ定義
#
- name: "Disable Gui"
  ansible.builtin.import_tasks: disable-gui.yml
- name: "Sysctl"
  ansible.builtin.import_tasks: sysctl.yml
- name: "Reboot Node"
  ansible.builtin.import_tasks: reboot-node.yml
