#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#
# Dockerサービス再起動ハンドラ
#

- name: Docker_restarted # notify の docker_restarted に対応
  listen: docker_restarted
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted
