#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
- name: "Docker"
  ansible.builtin.import_tasks: docker.yml
- name: "Sysctl"
  ansible.builtin.import_tasks: sysctl.yml
