#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  sysctl設定適用ハンドラ
#

- name: Apply_sysctl
  ansible.builtin.command: sysctl --system
  listen: "apply_sysctl"
  register: _result
  changed_when: _result.rc == 0
