#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.

# chronyを再起動する
- name: Restart_chrony
  listen: "restart_chrony"
  ansible.builtin.systemd:
    name: "{{ ntp_server_chrony_service }}"
    state: restarted
    enabled: true
  become: true
