#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
- name: "Avahi"
  ansible.builtin.import_tasks: avahi.yml
- name: "Disable Gui"
  ansible.builtin.import_tasks: disable-gui.yml
- name: "Auto Remove"
  ansible.builtin.import_tasks: auto-remove.yml
- name: "Nm Handlers Rhel"
  ansible.builtin.import_tasks: nm-handlers-rhel.yml
- name: "Netplan Handlers Debian"
  ansible.builtin.import_tasks: netplan-handlers-debian.yml
- name: "Netplan"
  ansible.builtin.import_tasks: netplan.yml
- name: "Reload Sysctl"
  ansible.builtin.import_tasks: reload-sysctl.yml
