#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
# sysctlのリロードハンドラ
- name: Reload sysctl
  listen: "common_reload_sysctl"
  ansible.builtin.command: sysctl --system
  changed_when: false
  become: true
