apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "multus-cni.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "multus-cni.labels" . | nindent 4 }}
