#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  タスクメイン部
#
#  include_tasksで他のタスクを読み込む
#
---

# 最初に変数設定を読み直す ( role単独で実行可能とするため )
- include_tasks: load-params.yml
  when:
    - radvd_nic is defined
    - radvd_nic in ansible_facts.interfaces

- include_tasks: package.yml
  when:
    - radvd_nic is defined
    - radvd_nic in ansible_facts.interfaces

- include_tasks: directory.yml
  when:
    - radvd_nic is defined
    - radvd_nic in ansible_facts.interfaces

- include_tasks: user_group.yml
  when:
    - radvd_nic is defined
    - radvd_nic in ansible_facts.interfaces

- include_tasks: config.yml
  when:
    - radvd_nic is defined
    - radvd_nic in ansible_facts.interfaces

- include_tasks: service.yml
  when:
    - radvd_nic is defined
    - radvd_nic in ansible_facts.interfaces
