#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  Gitlab Runner 用 docker設定関連タスク
#
---
# Docker Registry 用証明書ディレクトリを用意する
- name: Ensure docker registry cert directory exists
  ansible.builtin.file:
    path: "/etc/docker/certs.d/{{ gitlab_hostname }}:{{ gitlab_registry_port }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

# GitLab が自己署名証明書を生成するまで待つ
- name: Wait for gitlab self-signed certificate
  ansible.builtin.stat:
    path: "{{ gitlab_ssl_cert_path }}"
  register: gitlab_cert_stat
  until: gitlab_cert_stat.stat.exists | default(false)
  retries: 150
  delay: 6
  become: true

# DockerにGitlab自己証明書の自己証明書を登録する
- name: Copy gitlab self-signed certificate to docker certs directory
  ansible.builtin.copy:
    src: "{{ gitlab_ssl_cert_path }}"
    dest: "/etc/docker/certs.d/{{ gitlab_hostname }}:{{ gitlab_registry_port }}/{{ gitlab_hostname }}.crt"
    remote_src: true
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - "restart_docker_for_gitlab"
