#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  サービス起動ハンドラ
#

- name: "Kubelet"
  ansible.builtin.import_tasks: kubelet.yml
- name: "Reload Firewall"
  ansible.builtin.import_tasks: reload-firewall.yml
- name: "Reboot Node"
  ansible.builtin.import_tasks: reboot-node.yml
