#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ファイル・ディレクトリ作成関連タスク
#
- name: "Make {{ k8s_cilium_config_dir }}"
  ansible.builtin.file:
    path: "{{ k8s_cilium_config_dir }}"
    state: directory
    mode: "755"

- name: "Make {{ k8s_multus_config_dir }}"
  ansible.builtin.file:
    path: "{{ k8s_multus_config_dir }}"
    state: directory
    mode: "755"

- name: "Make {{ k8s_whereabouts_config_dir }}"
  ansible.builtin.file:
    path: "{{ k8s_whereabouts_config_dir }}"
    state: directory
    mode: "755"
