#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  タスクメイン部
#
#  include_tasksで他のタスクを読み込む
#

# 最初に変数設定を読み直す ( role単独で実行可能とするため )
- ansible.builtin.include_tasks: load-params.yml
- ansible.builtin.include_tasks: package.yml
- ansible.builtin.include_tasks: directory.yml
- ansible.builtin.include_tasks: user_group.yml
- ansible.builtin.include_tasks: service.yml
- ansible.builtin.include_tasks: config-k8sctrlplane-firewall.yml
  when: enable_firewall | default(false,true)
- ansible.builtin.include_tasks: config-helm.yml
- ansible.builtin.include_tasks: config-k8s-helm-shell-completion.yml
- ansible.builtin.include_tasks: config-k8s-cilium-shell-completion.yml
- ansible.builtin.include_tasks: config.yml
- ansible.builtin.include_tasks: config-cilium.yml
- ansible.builtin.include_tasks: config-cilium-bgp-cplane.yml
  when:
    - k8s_bgp is defined
    - k8s_bgp.enabled | default(false)
- ansible.builtin.include_tasks: config-cluster-mesh-tools.yml
