#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ロール固有変数のデフォルト値
#  group_vars/all/all.yml やhost_varsで上書き可能とするため,
#  ロール名/defaults/main.yml に定義している

# 再起動後の応答待ちのタイムアウト時間 (秒)
reboot_timeout_sec: 600

# SE Linux の設定
# 'enforcing', 'permissive', 'disabled' のいずれかを指定
common_selinux_state: "permissive"
# SELinux ポリシーモジュールの自動再ラベル付けを強制的に実施する
force_relabel: false
