#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#  ファイル・ディレクトリ作成関連タスク
# /usr/local/sbin を作成する
- name: "create {{ ddns_client_update_sh_dest_dir }}"
  ansible.builtin.file:
    path: "{{ ddns_client_update_sh_dest_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

# /usr/local/sbin/mount-nfs.sh を作成する
- name: "Create mount-nas.sh"
  ansible.builtin.template:
    src: mount-nas.sh.j2
    dest: "/usr/local/sbin/mount-nas.sh"
    owner: root
    group: root
    mode: 0755
    backup: true
