#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ファイル・ディレクトリ作成関連タスク
#

# 自己証明書格納先ディレクトリの作成
- name: "Create {{ rancher_cert_dir }} for self signed certification"
  ansible.builtin.file:
    path: "{{ rancher_cert_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"

# データの永続化用ディレクトリの作成
- name: "Create {{ rancher_data_dir }} for persistent data"
  ansible.builtin.file:
    path: "{{ rancher_data_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"
