#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#  aspell関連ファイル・ディレクトリ作成関連タスク

#
# aspell.confのスケルトン
#
- name: Deploy a aspell.conf
  ansible.builtin.template:
    src: _aspell.conf.j2
    dest: /etc/skel/.aspell.conf
    owner: root
    group: root
    mode: 0644
    backup: no
