#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#  tmux関連ファイル・ディレクトリ作成関連タスク

#
# tmux.confのスケルトン
#
- name: Deploy a tmux.conf
  ansible.builtin.template:
    src: _tmux.conf.j2
    dest: /etc/skel/.tmux.conf
    owner: root
    group: root
    mode: 0644
    backup: no
