#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#  wget関連ファイル・ディレクトリ作成関連タスク

#
# wgetrc
#
- name: Create /etc/skel/.wgetrc
  ansible.builtin.template:
    src: _wgetrc.j2
    dest: /etc/skel/.wgetrc
    owner: root
    group: root
    mode: 0644
    backup: no
