#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#  gdb関連ファイル・ディレクトリ作成関連タスク

#
# .gdbinitのスケルトン
#
- name: Deploy a .gdbinit
  ansible.builtin.template:
    src: _gdbinit.j2
    dest: /etc/skel/.gdbinit
    owner: root
    group: root
    mode: 0644
    backup: no
