#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#  screen関連ファイル・ディレクトリ作成関連タスク

#
# screenrcのスケルトン
#
- name: Deploy a screenrc
  ansible.builtin.template:
    src: _screenrc.j2
    dest: /etc/skel/.screenrc
    owner: root
    group: root
    mode: 0644
    backup: no
