#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  パッケージ関連処理
#
#
- name: "Install NTP client packages: {{ ntp_client_packages }}"
  ansible.builtin.package:
    name: "{{ ntp_client_packages }}"
    state: present
  become: true
