#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  タスクメイン部
#
#  include_tasksで他のタスクを読み込む
#

# 最初に変数設定を読み直す ( role単独で実行可能とするため )
- name: "Load Params"
  ansible.builtin.include_tasks: load-params.yml
# config-common-kubeconfig-tools.yml より先に実行する必要がある
- name: "Directory"
  ansible.builtin.include_tasks: directory.yml
- name: "Config Sudoer Path"
  ansible.builtin.include_tasks: config-sudoer-path.yml
- name: "Package"
  ansible.builtin.include_tasks: package.yml
- name: "Packages K8S Python"
  ansible.builtin.include_tasks: packages-k8s-python.yml
- name: "Config K8S Shell Completion"
  ansible.builtin.include_tasks: config-k8s-shell-completion.yml
- name: "Config Firewall Common"
  ansible.builtin.include_tasks: config-firewall-common.yml
- name: "Config Disable Swap"
  ansible.builtin.include_tasks: config-disable-swap.yml
- name: "Config Kubelet"
  ansible.builtin.include_tasks: config-kubelet.yml
- name: "Config Cpu Shielding"
  ansible.builtin.include_tasks: config-cpu-shielding.yml
- name: "Config Common Kubeconfig Tools"
  ansible.builtin.include_tasks: config-common-kubeconfig-tools.yml
- name: "Config"
  ansible.builtin.include_tasks: config.yml
- name: "User Group"
  ansible.builtin.include_tasks: user_group.yml
- name: "Config K8S Operator Authorized Keys"
  ansible.builtin.include_tasks: config-k8s-operator-authorized_keys.yml
- name: "Service"
  ansible.builtin.include_tasks: service.yml
