#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#  サービス起動ハンドラ

# 処理を直接書かずにincludeする
# 例:
# - import_tasks: docker.yml

- name: "Restart Named"
  ansible.builtin.import_tasks: restart-named.yml
- name: "Named Check Conf"
  ansible.builtin.import_tasks: named-check-conf.yml
- name: "Reload Zone"
  ansible.builtin.import_tasks: reload-zone.yml
- name: "Disable Gui"
  ansible.builtin.import_tasks: disable-gui.yml
