#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#

- name: Named_check_conf # notify の named_check_conf に対応
  listen: "named_check_conf"
  ansible.builtin.shell: |
      named-checkconf -z
  become: true
  changed_when: false
