#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#

- name: reload_zone  # notify の reload_zone に対応
  listen: reload_zone
  ansible.builtin.shell: |
    rndc reload
  become: true
