#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
# notify の Reload systemd & restart named に対応

# systemd のデーモンリロードを実施
- name: "Execute systemd daemon-reload"
  listen: "Reload systemd & restart named"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

# named の再起動
- name: "Restart named"
  listen: "Reload systemd & restart named"
  become: true
  ansible.builtin.systemd:
    name: "{{ dns_bind_service }}"
    state: restarted
    enabled: true
