#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ファイル・ディレクトリ作成関連タスク
#
- name: "Ensure chrony drop-in directory:{{ ntp_server_chrony_conf_drop_in_dir }} exists"
  ansible.builtin.file:
    path: "{{ ntp_server_chrony_conf_drop_in_dir }}"
    state: directory
    mode: "0755"
