#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ロール固有変数のデフォルト値
#  group_vars/all/all.yml やhost_varsで上書き可能とするため,
#  ロール名/defaults/main.yml に定義している
################################################################################
# 追加ルート定義
################################################################################
# 追加ルート定義リスト all-config.yml やhost_vars/ホスト名.yml で上書き可能
# 各要素の定義項目
#  - address_family: 'ipv4' または 'ipv6'
#  - destination: 宛先ネットワークアドレス/プレフィックス長
#    gateway: ゲートウエイアドレス
#    metric: メトリック値 ( オプション )
#
# 例:
# additional_network_routes:
#  - address_family: 'ipv4'
#    destination: "192.168.30.0/24"
#    gateway: "192.168.30.10"
#  - address_family: 'ipv6'
#    destination: "fdad:ba50:248b:1::/64"
#    gateway: "fdad:ba50:248b:1::10"
additional_network_routes: []
