#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  ロール固有変数のデフォルト値
#  group_vars/all/all.yml やhost_varsで上書き可能とするため,
#  ロール名/defaults/main.yml に定義している
---
netgauge_basename: "netgauge-{{ netgauge_version }}"
netgauge_archive: "{{ netgauge_basename }}.tar.gz"
netgauge_URL: "https://htor.inf.ethz.ch/research/netgauge/{{ netgauge_archive }}"
netgauge_dir: "/opt/netgauge"
netgauge_configure: "--with-mpi=no --prefix={{ netgauge_dir }}"
netgauge_build_dest: "/tmp/netgauge"
