#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  設定関連タスク
#

- name: Include ubuntu package names
  ansible.builtin.include_vars: ../vars/packages-ubuntu.yml
  when: ansible_facts.os_family == 'Debian'

- name: Include RHEL package names
  ansible.builtin.include_vars: ../vars/packages-rhel.yml
  when: ansible_facts.os_family == 'RedHat'

- name: Include cross-distro.yml
  ansible.builtin.include_vars: ../vars/cross-distro.yml

- name: Include config vars
  ansible.builtin.include_vars: ../vars/all-config.yml

- name: Include k8s api address vars
  ansible.builtin.include_vars: ../vars/k8s-api-address.yml
