#  -*- coding:utf-8 mode:yaml -*-
#  Ansible playbook
#  Copyright 2020 Takeharu KATO All Rights Reserved.
#
#  サービス起動ハンドラ
#

- name: "Restart Docker"
  ansible.builtin.import_tasks: restart-docker.yml
- name: "Reload Sysctl"
  ansible.builtin.import_tasks: reload-sysctl.yml
